version: "3.9"
services:
  web-server:
    build:
      context: .
      dockerfile: ./docker/web-server/Dockerfile
    container_name: weather-api
    ports:
      - "5000:5000"
    volumes:
    - .:/src/build
    depends_on:
      - mongo
    environment:
      FLASK_DEBUG: "true"
  mongo:
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - mongoDB-data:/data/db
  tests:
    build:
      context: .
      dockerfile: ./docker/web-server/Dockerfile
    volumes:
      - .:/src/build
    command: pytest --capture=no
volumes:
  mongoDB-data: