version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
    - .:/src/build
    depends_on:
      - mongo
    environment:
      FLASK_DEBUG: "true"
  mongo:
    image: mongo
    restart: always
    ports:
     - "27017:27017"
    volumes:
     - mongoDB-data:/data/db
volumes:
  mongoDB-data: